--INSERT INTO bebida (id, nombre, precio, dtype) VALUES (1, 'Cerveza', 3, 'con_alcohol');
--INSERT INTO bebida (id, nombre, precio, dtype) VALUES (2, 'Vino Tinto', 10, 'con_alcohol');
--INSERT INTO bebida (id, nombre, precio, dtype) VALUES (3, 'Whisky', 25, 'con_alcohol');
--INSERT INTO bebida (id, nombre, precio, dtype) VALUES (4, 'Agua Mineral', 1, 'sin_alcohol');
--INSERT INTO bebida (id, nombre, precio, dtype) VALUES (5, 'Zumo de Naranja', 2, 'sin_alcohol');
